In [35]:
import pandas as pd
import numpy as np
df=pd.read_csv('breast_cancer.csv')

In [36]:
df.shape

(213, 11)

In [37]:
df.head()

,S/N,Year,Age,Menopause,Tumor Size (cm),Inv-Nodes,Breast,Metastasis,Breast Quadrant,History,Diagnosis Result
0,1,2019,40,1,2,0,Right,0,Upper inner,0,Benign
1,2,2019,39,1,2,0,Left,0,Upper outer,0,Benign
2,3,2019,45,0,4,0,Left,0,Lower outer,0,Benign
3,4,2019,26,1,3,0,Left,0,Lower inner,1,Benign
4,5,2019,21,1,1,0,Right,0,Upper outer,1,Benign

In [38]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df = df.drop(columns=['s/n'])
df

,year,age,menopause,tumor_size_(cm),inv-nodes,breast,metastasis,breast_quadrant,history,diagnosis_result
0,2019,40,1,2,0,Right,0,Upper inner,0,Benign
1,2019,39,1,2,0,Left,0,Upper outer,0,Benign
2,2019,45,0,4,0,Left,0,Lower outer,0,Benign
3,2019,26,1,3,0,Left,0,Lower inner,1,Benign
4,2019,21,1,1,0,Right,0,Upper outer,1,Benign
...,...,...,...,...,...,...,...,...,...,...
208,2020,49,1,6,3,Right,1,Lower inner,1,Malignant
209,2020,28,1,3,0,Left,0,Upper inner,0,Benign
210,2020,22,1,1,0,Left,0,Upper outer,1,Benign
211,2020,19,1,1,0,Left,0,Lower inner,1,Benign
212,2020,50,0,4,0,Right,0,Lower outer,1,Benign

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              213 non-null    object
 1   age               213 non-null    int64
 2   menopause         213 non-null    int64
 3   tumor_size_(cm)   213 non-null    object
 4   inv-nodes         213 non-null    object
 5   breast            213 non-null    object
 6   metastasis        213 non-null    object
 7   breast_quadrant   213 non-null    object
 8   history           213 non-null    object
 9   diagnosis_result  213 non-null    object
dtypes: int64(2), object(8)
memory usage: 16.8+ KB

In [40]:
bad_numeric_cols = ['year','inv-nodes','tumor_size_(cm)']
for col in bad_numeric_cols:
     df[col] = pd.to_numeric(df[col], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              212 non-null    float64
 1   age               213 non-null    int64
 2   menopause         213 non-null    int64
 3   tumor_size_(cm)   212 non-null    float64
 4   inv-nodes         212 non-null    float64
 5   breast            213 non-null    object
 6   metastasis        213 non-null    object
 7   breast_quadrant   213 non-null    object
 8   history           213 non-null    object
 9   diagnosis_result  213 non-null    object
dtypes: float64(3), int64(2), object(5)
memory usage: 16.8+ KB

In [41]:
df.isna().sum()
df.dropna(inplace=True)
print(df.shape)

(212, 10)

In [42]:
text_columns = df.select_dtypes(include=['object']).columns
for col in text_columns:
    print(df[col].unique())
    print("\n")

['Right' 'Left' '#']


['0' '1']


['Upper inner' 'Upper outer' 'Lower outer' 'Lower inner' '#'
 'Upper outer ']


['0' '1' '#']


['Benign' 'Malignant']

In [43]:
df=df.replace("#",np.nan)
df['Breast Quadrant'] = df['Breast Quadrant'].str.strip()
df.dropna(inplace=True)

KeyError: 'Breast Quadrant'

In [44]:
print(df.describe())

              year         age   menopause  tumor_size_(cm)   inv-nodes
count   212.000000  212.000000  212.000000       212.000000  212.000000
mean   2019.523585   39.811321    0.665094         4.268868    0.353774
std       0.500626   14.124439    0.473075         2.571881    0.508072
min    2019.000000   13.000000    0.000000         1.000000    0.000000
25%    2019.000000   30.000000    0.000000         2.000000    0.000000
50%    2020.000000   40.000000    1.000000         4.000000    0.000000
75%    2020.000000   49.250000    1.000000         6.000000    1.000000
max    2020.000000   77.000000    1.000000        14.000000    3.000000

In [45]:
text_cols = df.select_dtypes(include=['object']).columns
for col in text_cols:
    print(df[col].value_counts())

breast
Left     107
Right    100
Name: count, dtype: int64
metastasis
0    139
1     73
Name: count, dtype: int64
breast_quadrant
Upper outer     67
Lower outer     54
Upper inner     45
Lower inner     44
Upper outer      1
Name: count, dtype: int64
history
0    124
1     87
Name: count, dtype: int64
diagnosis_result
Benign       120
Malignant     92
Name: count, dtype: int64

KeyError: 'Diagnosis Result'

In [47]:
import numpy as np
df = df.replace('#', np.nan)
df = df.dropna()

In [48]:
print(df.columns.tolist())

['year', 'age', 'menopause', 'tumor_size_(cm)', 'inv-nodes', 'breast', 'metastasis', 'breast_quadrant', 'history', 'diagnosis_result']